feat(tailwind): Add font-size aliases for text utilities
axa-ch/design-tokens pull request #5
Opened 2024-10-09 13:02 UTC by fkapsahili

This PR introduces new font-size aliases (`sm`, `base`, `lg`, `xl`) to the existing `text-<number>` utilities to the Tailwind configuration. The current config generates classes like `text-text-1`, which can seem unintuitive and redundant. Additionally, the existing setup prevents the use of default Tailwind utilities such as `text-sm` and `text-base`.

### Prerequisites
- [x] Use a meaningful title for the pull request
- [x] Test the changes you've made by adding or editing tests

### Content
- Added font-size aliases for text utilities in the Tailwind configuration
- Preserved backward compatibility with existing text utilities

### Tests
- Added tests to ensure that the new font-size aliases are correctly generated and mapped to their respective `text-<number>` parts
- Verified backward compatibility by testing the existence of `text-<number>` utilities.

2024-10-09 14:18 UTC, GianlucaGuarini commented
Thank you for your contribution. Wouldn't be easier to add directly these aliases as tokens [here](https://github.com/axa-ch/design-tokens/blob/main/tokens/globals/typography/text.json)?

For example

```json
"text-xl": { "value": "{typography.text-1}" }
```

2024-10-09 16:58 UTC, fkapsahili commented
> Thank you for your contribution. Wouldn't be easier to add directly these aliases as tokens [here](https://github.com/axa-ch/design-tokens/blob/main/tokens/globals/typography/text.json)?
> 
> For example
> 
> ```json
> "xl": { "value": "{typography.text-1}" }
> ```

@GianlucaGuarini Thanks for looking into it!

Yes, that could make sense. I adjusted the config to generate e.g. `text-1` instead of `text-text-1` for the Tailwind class names, and it will produce additional utilities like `text-base`, `text-sm`, `text-lg`, and `text-xl` for overriding the built-in Tailwind class names.

Also, updating the token definitions in `text.json` will not only generate tokens for Tailwind classes, but also create tokens for other platforms, since it affects the overall token generation; but I guess that's fine? 🙂

2024-10-10 06:26 UTC, GianlucaGuarini commented
@domirs can you please have a look at it as well? 

> Yes, that could make sense. I adjusted the config to generate e.g. text-1 instead of text-text-1 for the Tailwind class names, and it will produce additional utilities like text-base, text-sm, text-lg, and text-xl for overriding the built-in Tailwind class names.

Isn't this technically a breaking change? Probably we need to bump a new major release for it

2024-10-10 06:34 UTC, GianlucaGuarini requested changes

2024-10-10 06:34 UTC, GianlucaGuarini commented on formats/tailwind/get-font-size.js
> +      [token.name.replace('typography-', '').replace('text-', '')]: [
I think that the `text-` chunk should be only replaced for the aliases to preserve the backward compatibility. Please add also a TODO note to inform that we will need to replace it in future for all the `typography` tokens

2024-10-10 06:34 UTC, GianlucaGuarini commented on package.json
> +  "version": "2.2.0",
please avoid bumping the `package.json` version in a PR

2024-10-10 06:48 UTC, fkapsahili commented
@GianlucaGuarini 

I’ve updated the config to only remove the `text-` prefix for built-in Tailwind class names (`text-sm`, `text-base`, etc.). This preserves existing generated tokens like `text-text-1` etc, but I think that's fine for now.

I think considering reducing redundancy in other `text-` tokens in the future would be useful, but for now, this keeps things stable and improves Tailwind usage.

2024-10-10 07:35 UTC, GianlucaGuarini approved these changes

2024-10-10 07:49 UTC, domirs approved these changes

2024-10-10 07:49 UTC, merged

2024-10-10 07:50 UTC, GianlucaGuarini commented
Thank you @fkapsahili for your contribution. We will inform our design team that these tokens might need to be renamed in future